Metrics/MethodLength:
  Exclude:
    - 'db/migrate/20241007102726_create_active_storage_tables.active_storage.rb'
    - 'db/migrate/20241016050120_create_players.rb'
    - 'db/migrate/20241111084134_create_stadia.rb'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/20241007102726_create_active_storage_tables.active_storage.rb'

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'